name: Pipeline
on: [push]
jobs:

  publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      MKDOCS_VER: "1.3.1"
    steps:
      - name: Install mkdocs
        run: mkdir ~/env && python3 -m venv ~/env/mkdocs && source ~/env/mkdocs/bin/activate && pip install --upgrade pip && pip install mkdocs==${MKDOCS_VER}

      - name: Verify mkdocs install
        run: source ~/env/mkdocs/bin/activate && mkdocs --version

#      - name: Checkout Content Repo
#        uses: actions/checkout@v3
#        with:
#          repository: 'wlieberz/github-user-page-content'
#          path: './repos/github-user-page-content'
#
#      - name: Checkout Serving Repo
#        uses: actions/checkout@v3
#        with:
#          repository: 'wlieberz/wlieberz.github.io'
#          path: './repos/wlieberz.github.io'

