name: Pipeline
on: [push]
jobs:

  publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Content Repo
        uses: actions/checkout@v3
        with:
          repository: 'wlieberz/github-user-page-content'
          path: './repos/github-user-page-content'

      - name: Checkout Serving Repo
        uses: actions/checkout@v3
        with:
          repository: 'wlieberz/wlieberz.github.io'
          path: './repos/wlieberz.github.io'

      - name: Verify After Checkout
        run: echo REPOS DIR CONTENTS && ls -lh ./repos/ && echo CONTENT REPO CONTENTS && ls -l ./repos/wlieberz.github.io/
