name: Pipeline
on: [push]
jobs:

  publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Content Repo
      - uses: actions/checkout@v3
        with:
          repository: 'https://github.com/wlieberz/github-user-page-content'

      - name: Verify Checkout
        run: pwd && ls -lh
