name: Pipeline
on: [push]
jobs:

  publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Verify Before Checkout
        run: pwd && ls -lh

      - name: Checkout Content Repo
        uses: actions/checkout@v3
        with:
          repository: 'wlieberz/github-user-page-content'
          path: './repos/github-user-page-content'

      - name: Verify After Checkout
        run: pwd && ls -lh && ls -lh ./repos/ && ls -lha ./repos/github-user-page-content/
